# Generated by Django 4.2.16 on 2024-12-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='group_photo',
            field=models.ImageField(null=True, upload_to='group_photos/'),
        ),
    ]
