# Generated by Django 4.2.16 on 2024-12-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_groupchat_group_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='group_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='group_username',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
